
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/tmp/pip-build-env-j313kjyn/overlay/local/lib/python3.10/dist-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.8.0-49-generic - x86_64
...
